### ISSUE TITLE
Does not run on Apple Silicon

### ISSUE THREAD

**Issue by marjue12255** [kmgrant/macterm#5] opened 2022-01-07 12:39 UTC
/Applications/MacTerm.app/Contents/MacOS/MacTerm

MacTerm: Some variant of Python 2.x (or less) is running.
WARNING: Your OS version hasn't been tested with this MacTerm version.  Visit 'https://www.macterm.net/' to check for updates or report bugs.
MacTerm: Latest preferences are version 8 and user preferences are version 0.
Exception raised while attempting to run /Applications/MacTerm.app/Contents/MacOS/MacTerm_python2.6_wrap ['/Applications/MacTerm.app/Contents/MacOS/MacTerm_python2.6_wrap', **'/Applications/MacTerm.app/Contents/MacOS/RunApplication.py'] : [Errno 86] Bad CPU type in executable**

**Comment by kmgrant** [comment] 2022-01-07 16:40
Hi,
MacTerm definitely runs on Apple Silicon (my development machine is an M1).

From the log above, you do not seem to be using the latest code, since it has since changed to Python 3.x.

Please `git pull` to the latest code, use a Python 3.x installation and see if the issue is still present.

**Comment by marjue12255** [comment] 2022-01-07 16:54
Hello
Sorry for this misunderstanding. I have downloaded a pre build 4.1. I have to get familiar with building a binary from source first. Then I will try the version 5 beta.

**Comment by kmgrant** [comment] 2022-01-07 17:00
No problem.  Unfortunately 4.1 builds do not work on macOS 10.15 (Catalina) or any later version, because Apple made significant changes to the system at that point.

Yes, you currently need to build from source to try 5.0.  I do plan to make pre-builds eventually but note that some features are not working smoothly yet; I had to redo several things to make MacTerm work after 10.15.

**Comment by kmgrant** [comment] 2022-01-24 02:48
I will close this issue for now (since it is related to Apple Silicon, which MacTerm 5 supports).  If you have any issues with the build, please contact me separately.

**Closed by kmgrant** 2022-01-24 02:48 UTC
