### ISSUE TITLE
Cannot handle SIXELs generated by ImageMagick.

### ISSUE THREAD

**Issue by saitoha** [kmgrant/macterm#2] opened 2017-12-12 14:06 UTC
I tried Version 4.1.0b, build 20171211.

<img width="1084" alt="macterm" src="https://user-images.githubusercontent.com/1162739/33888544-b5cb85a4-df90-11e7-9539-d5cc4711c153.png">

**Comment by kmgrant** [comment] 2017-12-12 20:13
I am not able to reproduce this behavior, unless I turn off Sixels completely.  Please look in Preferences, Terminals category, Emulation tab; the box "VT340 Sixel Graphics" should be checked.  Also, when you create your session, be sure to select a Terminal where you have enabled this setting (if you have more than one).

Note that I sent the input using the script below, converted to ".txt" for upload:

[test_issue_2.sxl.sh.txt](https://github.com/kmgrant/macterm/files/1553119/test_issue_2.sxl.sh.txt)

The output is as follows; I also ran `xxd` and see the same data:

<img width="556" alt="issue_2_1" src="https://user-images.githubusercontent.com/853344/33905742-735bd22a-df34-11e7-8232-7b46104cbcac.png">

I also ran `convert` with `six:-` on some images and they appear to be displayed correctly.

**Comment by kmgrant** [comment] 2019-01-29 03:13
This may actually be the same problem as issue #3; the terminal type needs to be set to VT220 or XTerm when the image program queries the terminal.  (The default type in MacTerm 4.1 is VT100, which does not have a Sixel query.)

If you change the default MacTerm terminal type to VT220 or XTerm, `convert` should work as expected.

For example:
1. In the MacTerm menu, select “Preferences”; from the Preferences window, go to the “Terminals” category.
1. Select “Default” on the left-hand side to modify the default behavior for new terminal windows.
1. Select the “Emulation” tab.
1. Under “**Base Emulator:**”, select XTerm from the menu.
1. Under “**Identity:**”, enter “xterm-256color”.
1. Under “**Emulation Tweaks:**”, ensure “VT340 Sixel Graphics” is checked (it should be by default).
1. Open a new terminal window to use the new settings.  (Existing windows will not be affected.)

**Comment by kmgrant** [comment] 2019-05-12 15:49
Closing issue based on remedy above.

**Closed by kmgrant** 2019-05-12 15:49 UTC
